// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo1PNdzKsRBnsH1Eq7Tx54NfYOQj76Vbc',
    appId: '1:179147005811:web:ab9c1a73893a23358f6f06',
    messagingSenderId: '179147005811',
    projectId: 'athlete-fe086',
    authDomain: 'athlete-fe086.firebaseapp.com',
    storageBucket: 'athlete-fe086.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwtPnC4i49ivUTIFek2wMnpcluzOCaohg',
    appId: '1:179147005811:android:824b93e2a671dec68f6f06',
    messagingSenderId: '179147005811',
    projectId: 'athlete-fe086',
    storageBucket: 'athlete-fe086.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_ztZk6EsoFcTHDtcsc8xYPAqQx_iy8I8',
    appId: '1:179147005811:ios:f52ade12811ad83f8f6f06',
    messagingSenderId: '179147005811',
    projectId: 'athlete-fe086',
    storageBucket: 'athlete-fe086.firebasestorage.app',
    iosBundleId: 'com.example.athlete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_ztZk6EsoFcTHDtcsc8xYPAqQx_iy8I8',
    appId: '1:179147005811:ios:f52ade12811ad83f8f6f06',
    messagingSenderId: '179147005811',
    projectId: 'athlete-fe086',
    storageBucket: 'athlete-fe086.firebasestorage.app',
    iosBundleId: 'com.example.athlete',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo1PNdzKsRBnsH1Eq7Tx54NfYOQj76Vbc',
    appId: '1:179147005811:web:db0e6b560277d40a8f6f06',
    messagingSenderId: '179147005811',
    projectId: 'athlete-fe086',
    authDomain: 'athlete-fe086.firebaseapp.com',
    storageBucket: 'athlete-fe086.firebasestorage.app',
  );

}